/*  BSD License
    Copyright (c) 2014 Andrey Chilikin https://github.com/achilikin

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/

/**
    Basic BDF Exporter - converts BDF files to C structures.
    Only 8 bits wide fonts are supported.
*/
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "bdf.h"

const char *filename(const char *name);

// check if 'buf' starts with 'key' and store pointer to the argument
static char *key_arg(char *buf, const char *key, char **arg)
{
    char *end;
    size_t len = strlen(key);

    if (strncmp(buf, key, len) == 0)
    {
        end = buf + len;
        if (*end > ' ')
            return NULL;
        if (arg == NULL)
            return buf;
        for (; *end <= ' ' && *end != '\0'; end++)
            ;
        *arg = end;
        return buf;
    }

    return NULL;
}

// rotate glyph bitmap CCW
// static uint32_t rotate_glyph(const uint8_t *glyph, unsigned gw, int gh, uint8_t *grot)
// {
// 	uint32_t dy = 0;

// 	do {
// 		for(uint8_t n = 0; n < gw; n++) {
// 			uint8_t out = 0;
// 			uint8_t mask = 0x80 >> n;
// 			for(uint8_t b = 0; b < 8; b++) {
// 				if (glyph[b] & mask)
// 					out |= 1 << b;
// 			}
// 			grot[dy++] = out;
// 		}
// 		glyph += 8;
// 	} while((gh -= 8) > 0);

// 	return dy;
// }

void print_glyph(const uint8_t *glyph, unsigned gw, unsigned gh)
{
    // printf("gw: %d   gh: %d\n", gw, gh);
    for (int i = 0; i < gh; i++)
    {
        uint16_t word = glyph[0 + (i * 2)] << 8 | glyph[1 + (i * 2)];
        // printf(" 0x%02X //  %2d|", gout[i], i);
        printf(" 0x%02X, 0x%02X //  %2d|", (uint8_t)(word), (uint8_t)(word >> 8), i);
        for (unsigned bit = 0; bit < gw; bit++)
        {
            if (word > 255)
            {
                if (bit < 8)
                {
                    printf("%c", (word & (0x80 >> bit)) ? '#' : ' ');
                }
                else
                {
                    printf("%c", (word & (0x8000 >> bit)) ? '#' : ' ');
                }
            }
            else
            {
                if (word & (0x80 >> bit))
                    printf("#");
                else
                    printf(" ");
            }
        }
        printf("|\n");
    }
}

int bdf_convert(const char *name, unsigned gmin, unsigned gmax, unsigned ascender, int flags)
{
    FILE *fp;
    char *arg;
    char buf[BUFSIZ];
    char startchar[BUFSIZ];

    if (name == NULL || (fp = fopen(name, "r")) == NULL)
        return 0;

    memset(buf, 0, sizeof(buf));
    int mute = flags & BDF_MUTE;

    if (!mute && (flags & BDF_HEADER))
    {
        printf("// File generated by 'bdfe");
        if (flags & BDF_NATIVE)
            printf(" -n");
        if (flags & BDF_ROTATE)
            printf(" -r");
        if (ascender)
            printf(" -a %d", ascender);
        printf(" -s %d-%d %s'\n", gmin, gmax, filename(name));
    }
    // parse file header up to 'CHARS' keyword
    unsigned dx = 0, dy = 0, ascent = 0;
    while (fgets(buf, sizeof(buf) - 2, fp) != NULL)
    {
        arg = strchr(buf, '\0');
        while (*arg < ' ' && arg != buf)
            *arg-- = '\0';

        if (!mute && (flags & BDF_HEADER))
        {
            if (key_arg(buf, "FONT", &arg))
                printf("// %s\n", buf);
            if (key_arg(buf, "COMMENT", &arg))
                printf("// %s\n", buf);
            if (key_arg(buf, "COPYRIGHT", &arg))
                printf("// %s\n", buf);
            if (key_arg(buf, "FONT_ASCENT", &arg))
                printf("// %s\n", buf);
        }

        if (key_arg(buf, "FONTBOUNDINGBOX", &arg))
        {
            if (!mute && (flags & BDF_HEADER))
                printf("// %s\n", buf);
            dx = strtoul(arg, &arg, 10);
            dy = strtoul(arg, &arg, 10);
            strtoul(arg, &arg, 10);
            strtoul(arg, &arg, 10);
        }
        if (key_arg(buf, "FONT_ASCENT", &arg))
        {
            if (!mute && (flags & BDF_HEADER))
                printf("// %s\n", buf);
            ascent = strtoul(arg, &arg, 10);
        }
        if (key_arg(buf, "FONT_DESCENT", &arg))
        {
            if (!mute && (flags & BDF_HEADER))
                printf("// %s\n", buf);
            strtoul(arg, &arg, 10);
        }

        if (key_arg(buf, "CHARS", &arg))
        {
            // nchars = atoi(arg);
            break;
        }
    }

    if (dy == 0)
    {
        fclose(fp);
        return 0;
    }

    // recalculate glyphs x size as we cannot use FONTBOUNDINGBOX
    // as it is for our gmin/gmax range
    dx = 0;
    while (fgets(buf, sizeof(buf) - 2, fp) != NULL)
    {
        if (key_arg(buf, "STARTCHAR", &arg))
        {
            unsigned idx = 0, dw;

            while (fgets(buf, sizeof(buf) - 2, fp) != NULL)
            {
                if (key_arg(buf, "ENCODING", &arg))
                {
                    idx = atoi(arg);
                    if (idx < gmin || idx > gmax)
                        break;
                }
                if (key_arg(buf, "DWIDTH", &arg))
                {
                    dw = atoi(arg);
                    if (dw > dx)
                        dx = dw;
                    break;
                }
            }
        }
    }

    unsigned gh = dy, gw = dx;

    if (!mute && (flags & BDF_HEADER))
        printf("// Converted Font Size %dx%d\n\n", dx, dy);
    if (ascender > dy / 2)
        ascender = dy / 2;
    // rewind the file pointer ans start parsing glyphs
    fseek(fp, 0, SEEK_SET);

    unsigned gsize = (dy * ((dx + 7) / 8)) * 2;
    uint8_t *glyph = (uint8_t *)malloc(gsize);
    memset(glyph, 0, gsize);

    while (fgets(buf, sizeof(buf) - 2, fp) != NULL)
    {
        if (key_arg(buf, "STARTCHAR", &arg))
        {
            int displacement = 0;
            unsigned bitmap = 0, i = 0, idx = 0;
            unsigned bbw = 0, bbh = 0;
            int bbox = 0, bboy = 0;
            // store a copy in case if verbose output is on
            arg = strchr(buf, '\0');
            while (*arg < ' ' && arg != buf)
                *arg-- = '\0';
            strcpy(startchar, buf);

            while (fgets(buf, sizeof(buf) - 2, fp) != NULL)
            {
                arg = strchr(buf, '\0');
                while (*arg < ' ' && arg != buf)
                    *arg-- = '\0';

                if (key_arg(buf, "ENCODING", &arg))
                {
                    idx = atoi(arg);
                    if (idx < gmin || idx > gmax)
                        // break;
                    if (!mute && !(flags & BDF_GPL) && (flags & BDF_VERBOSE))
                    {
                        printf("// %s\n", startchar);
                        printf("// %s\n", buf);
                    }
                }
                if (key_arg(buf, "DWIDTH", &arg))
                {
                    // gw = atoi(arg);
                    // if (gw > 8)
                    // break;
                }
                if (key_arg(buf, "BBX", &arg))
                {
                    if (!mute && !(flags & BDF_GPL) && (flags & BDF_VERBOSE))
                        printf("// %s\n", buf);
                    bbw = strtol(arg, &arg, 10);
                    bbh = strtol(arg, &arg, 10); // skip bbh, we'll calculate it (i)
                    bbox = strtol(arg, &arg, 10);
                    bboy = strtol(arg, &arg, 10);
                }
                if (key_arg(buf, "ENDCHAR", &arg))
                {
                    bitmap = 0;
                    // Displacement caculation
                    // Ascent - Glyph BBX Y value + Glyph decent X value
                    displacement = ascent - bbh - bboy;

                    if (!mute)
                    {
                        // glyph per line
                        if (flags & BDF_GPL)
                        {
                            printf("\t");
                            for (i = 0; i < gh; i++)
                            {
                                if ((i == gh / 2) && (flags & BDF_ROTATE))
                                    printf("\n\t");
                                printf("0x%02X,", glyph[i]);
                            }
                            printf(" // %5d", idx);
                            if (isprint(idx))
                                printf(" '%c'", idx);
                            printf("\n");
                        }
                        else
                        {
                            if(gw > 8 ) {
                                printf("//      %5d '%c' |", idx, isprint(idx) ? idx : ' ');
                            }
                            else {
                                printf("// %5d '%c' |", idx, isprint(idx) ? idx : ' ');
                            }

                            for (i = 0; i < gw; i++)
                                printf("%d", i);
                            printf("|\n");

                            for (int disp_i = 0; disp_i < displacement; disp_i++)
                            {
                                if(gw > 8) {
                                    printf(" 0x00, 0x00, //  %2d|", disp_i);
                                }
                                else {
                                    printf(" 0x00, //  %2d|", disp_i);
                                }
                                for (unsigned bit = 0; bit < gw; bit++)
                                {
                                    printf(" ");
                                }
                                printf("|\n");
                            }

                            for (i = 0; i < (gh - displacement); i++)
                            {
                                uint16_t word = 0x0000;
                                if(gw > 8) {
                                    word = glyph[0 + (i * 2)] << 8 | glyph[1 + (i * 2)];
                                }
                                else {
                                    word = glyph[i];
                                }
                                // printf(" 0x%02X //  %2d|", gout[i], i);
                                if(gw > 8) {
                                    printf(" 0x%02X, 0x%02X, //  %2d|", (uint8_t)(word), (uint8_t)(word >> 8), (i+displacement));
                                }
                                else {
                                    printf(" 0x%02X, //  %2d|", (uint8_t)(word), (i+displacement));
                                }
                                // printf(" 0x%02X, 0x%02X, //  %2d|", (uint8_t)(word), (uint8_t)(word >> 8), (i+displacement));
                                for (unsigned bit = 0; bit < gw; bit++)
                                {
                                    if (word > 255)
                                    {
                                        if (bit < 8)
                                        {
                                            printf("%c", (word & (0x80 >> bit)) ? '#' : ' ');
                                        }
                                        else
                                        {
                                            printf("%c", (word & (0x8000 >> bit)) ? '#' : ' ');
                                        }
                                    }
                                    else
                                    {
                                        if (word & (0x80 >> bit))
                                            printf("#");
                                        else
                                            printf(" ");
                                    }
                                }
                                printf("|\n");
                            }
                            printf("\n");
                        }
                    }
                    break;
                }
                if (key_arg(buf, "BITMAP", &arg))
                {
                    bitmap = 1;
                    i = 0;
                    memset(glyph, 0x00, gsize);
                    continue;
                }
                if (bitmap && (i < gsize))
                {
                    uint16_t bitValue = 0;
                    bitValue = strtoul(buf, NULL, 16);
                    bitValue = bitValue >> bbox;

                    if(bbw > 8) {
                        if (bitValue > 255)
                        {
                            glyph[i++] = (uint8_t)(bitValue);
                            glyph[i++] = (uint8_t)(bitValue >> 8);
                        }
                        else
                        {
                            glyph[i++] = 0x00;
                            glyph[i++] = (uint8_t)(bitValue);
                        }
                    } else {
                        glyph[i++] = (uint8_t)(bitValue);
                    }
                    // }
                    // if (bitValue > 255)
                    // {
                    //     glyph[i++] = (uint8_t)(bitValue);
                    //     glyph[i++] = (uint8_t)(bitValue >> 8);
                    // }
                    // else
                    // {
                    //     glyph[i++] = 0x00;
                    //     glyph[i++] = (uint8_t)(bitValue);
                    // }
                    // (void)bbw;
                }
            }
        }
    }

    free(glyph);
    fclose(fp);
    return 0;
}
